// File generated by FlutterFire CLI
// This is a placeholder - you need to run:
// flutterfire configure
// to generate the actual file with your Firebase project configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbu_k5EgsWb1eY0OSjBObIWmRAWDPjFQ',
    appId: '1:1059546373368:android:677e358246b471c38faf0d',
    messagingSenderId: '1059546373368',
    projectId: 'silah-app-e0bb8',
    storageBucket: 'silah-app-e0bb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhiaWDr3-jNkCgf1LVuDAYQJPeY9jt9Vw',
    appId: '1:1059546373368:ios:5a64277058de33f88faf0d',
    messagingSenderId: '1059546373368',
    projectId: 'silah-app-e0bb8',
    storageBucket: 'silah-app-e0bb8.firebasestorage.app',
    iosBundleId: 'com.silah.silah',
  );
}
