import 'package:flutter/material.dart';

import 'core/app_theme.dart';
import 'core/api_client.dart';
import 'core/notification_service.dart';
import 'core/app_settings.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// Firebase options - will be generated by flutterfire configure
// Run: flutterfire configure
// For now, Firebase will initialize with default options if not configured
import 'ui/screens/splash_screen.dart';
import 'ui/screens/signup_screen.dart';
import 'ui/screens/login_screen.dart';
import 'ui/screens/forgot_password_screen.dart';
import 'ui/screens/reset_password_screen.dart';
import 'ui/screens/complete_profile_screen.dart';
import 'ui/screens/payment_post_profile_screen.dart';
import 'ui/screens/invoice_screen.dart';
import 'ui/shell/app_shell.dart';
import 'ui/screens/create_ad_screen.dart';
import 'ui/screens/payment_screen.dart';
import 'ui/screens/boost_activity_screen.dart';
import 'ui/screens/requests_screen.dart';
import 'ui/screens/settings_screen.dart';
import 'ui/screens/terms_screen.dart';
import 'ui/screens/privacy_screen.dart';
import 'ui/screens/help_screen.dart';
import 'ui/screens/help_detail_screen.dart';
import 'ui/screens/notifications_screen.dart';
import 'ui/screens/safety_tutorial_screen.dart';
import 'core/socket_service.dart';
import 'core/auth_api.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('Firebase initialized successfully');
  } catch (e) {
    // Firebase not configured yet - app will still work without push notifications
    print('Firebase initialization error: $e');
  }
  
  // Initialize API Client
  await ApiClient.instance.init();
  
  // Fetch app settings from backend
  try {
    await AppSettingsService.fetchSettings();
  } catch (e) {
    // Use default settings on error
    print('Failed to fetch app settings: $e');
  }
  
  // Initialize Notification Service (will handle Firebase initialization internally)
  try {
    await NotificationService.instance.initialize();
  } catch (e) {
    // Notifications will work without Firebase (in-app only)
    print('Notification service initialization failed: $e');
  }
  
  // Check if user is logged in and connect socket
  try {
    final prefs = await SharedPreferences.getInstance();
    final token = prefs.getString('auth_token');
    if (token != null) {
      // Get current user to get userId
      final authApi = AuthApi();
      final authResponse = await authApi.getMe();
      if (authResponse['success'] == true) {
        final user = authResponse['user'] as Map<String, dynamic>;
        final userId = user['_id'] ?? user['id'];
        if (userId != null) {
          await SocketService().connect(userId: userId.toString());
        }
      }
    }
  } catch (e) {
    print('Socket connection failed: $e');
  }
  
  runApp(const SilahApp());
}

class SilahApp extends StatelessWidget {
  const SilahApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Silah',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      initialRoute: SplashScreen.routeName,
      routes: {
        SplashScreen.routeName: (_) => const SplashScreen(),
        SignUpScreen.routeName: (_) => const SignUpScreen(),
        LoginScreen.routeName: (_) => const LoginScreen(),
        ForgotPasswordScreen.routeName: (_) => const ForgotPasswordScreen(),
        ResetPasswordScreen.routeName: (context) {
          final args = ModalRoute.of(context)?.settings.arguments;
          return ResetPasswordScreen();
        },
        CompleteProfileScreen.routeName: (context) {
          final args = ModalRoute.of(context)?.settings.arguments;
          return CompleteProfileScreen();
        },
        PaymentPostProfileScreen.routeName: (_) => const PaymentPostProfileScreen(),
        InvoiceScreen.routeName: (_) => const InvoiceScreen(),
        AppShell.routeName: (_) => const AppShell(),
        CreateAdScreen.routeName: (_) => const CreateAdScreen(),
        PaymentScreen.routeName: (_) => const PaymentScreen(),
        BoostActivityScreen.routeName: (context) {
          final args = ModalRoute.of(context)?.settings.arguments;
          return BoostActivityScreen();
        },
        RequestsScreen.routeName: (_) => const RequestsScreen(),
        SettingsScreen.routeName: (_) => const SettingsScreen(),
        TermsScreen.routeName: (_) => const TermsScreen(),
        PrivacyScreen.routeName: (_) => const PrivacyScreen(),
        HelpScreen.routeName: (_) => const HelpScreen(),
        HelpDetailScreen.routeName: (context) {
          return const HelpDetailScreen();
        },
        NotificationsScreen.routeName: (_) => const NotificationsScreen(),
        SafetyTutorialScreen.routeName: (_) => const SafetyTutorialScreen(),
      },
    );
  }
}

